### ISSUE TITLE
Tugevalt autenditud (isikukoodiga seotud) kasutaja saab oma nime muuta, kui logib sisse salasõna kasutades

### ISSUE THREAD

**Issue by joellimberg** [hariduspilv/harid#1]
Kui logida sisse Mobiil-ID'ga, ei saa /users/edit lehel konto nime muuta (nagu peakski olema). Aga kui samale kontole määrata salasõna ja sellega sisse logida, saab ikkagi nime muuta.

**Comment by Fornacula** [comment]
Täname tagasiside eest! Tuvastasime ka ise sama olukorra ning arendajale on info edastatud. Anname teada, kui vastavasisuline muudatus on üleval.

**Comment by Fornacula** [comment]
Probleem lahendatud
