### ISSUE TITLE
Sisse logimisel "Konto uuendamine" ei toimi

### ISSUE THREAD

**Issue by joellimberg** [hariduspilv/harid#11]
1. alustada näiteks lehelt https://moodle.hitsa.ee/
2. Klõps HarID nupul
3. Logida sisse Mobiil-ID-ga
4. ilmub leht "Enne jätkamist pead sa oma konto kinnitama" — vahemärkusena: **kui klõpsata kasutustingimuste lugemise lingil, avaneb tingimuste leht samas aknas, sisselogimisprotsess katkeb**
5. teha konto kinnitamise lehel "Nõustun kasutajatingimustega" linnuke
6. Klõps "Uuenda kontot" nupul
7. Moodle avanemise asemel logitakse kasutaja välja, ilmub veateade, ei avane Moodle.

<img width="620" alt="screen shot 2018-10-26 at 15 49 41" src="https://user-images.githubusercontent.com/875872/47567421-2ad79400-d937-11e8-90dc-fe429b5e5762.png">

**Comment by Fornacula** [comment]
Tänud teadamast! Probleem arusaadav ja arendajale teada antud.

**Comment by joellimberg** [comment]
Tere!

Mööda on läinud kuu aega, aga probleem ei ole ikka veel lahenenud, ja ma ei saa oma HarID kontole sisse logida.

Muutunud on see, et ülalkirjeldatud sammus 7 ilmuv veateade on nüüd punase asemel kollast värvi.

<img width="516" alt="screen shot 2018-11-27 at 12 08 19" src="https://user-images.githubusercontent.com/875872/49074354-33283500-f23d-11e8-8484-05aa02b074f3.png">

**Comment by priit** [comment]
Tere,

Tänud väga hea tagasiside eest, me oleme enda teada parandanud algse probleemi aga vaatame selle osa igaks juhuks uuesti üle. 

Samas hetkel võib olla probleem selles, et teie konto sai varajases staadiumis pihta ja on sellest ajast katki kuna me täna ei suuda teiste testkontodega viga korrata (mis ei tähenda, et viga ei ole).

Anname teada kui teie konto on korda tehtud.

Vabandust ebamugavuse pärast.

Priit

**Comment by joellimberg** [comment]
Tänan, nüüd toimis!

Kinnitamise protsessis oli kah UI-s midagi ikkagi natuke nihusti, aga unustasin käigult ekraanipilte teha.

Osaliselt mälu järgi:

- Saabunud kinnituslink oli kujul: http://harid.ee/et/users/confirmation?auth_provider=mobileid&confirmation_token=XXXXXX

- Seal klõpsates ilmus sisselogimisleht ilma mingi lisainfota või _OK/error_ teateta

- Aga tundub, et meiliaadress siiski kinnitati ära, nüüd saan kontot taas kasutada!

**Comment by Fornacula** [comment]
Super, mängime selle teise punkti olukorra ka läbi ja teeme vajadusel korrektuurid. Sulgen selle issue.
