### ISSUE TITLE
“Esindatavad” (e 'children') andmed läbi userinfo_endpoint-i

### ISSUE THREAD

**Issue by joellimberg** [hariduspilv/harid#2]
Tundub, et hetkel ei ole võimalik OpenID kaudu kuidagi teada saada sisse loginud kasutaja esindatavate infot.

Vaja oleks näiteks:

```
// userinfo
{
	...
	"roles": [...],
	"related_users": [
		{
			"sub": "0ab75adb-3333-46d7-22222-2222222",
			"name": "Lapse Nimi",
			"email": "...@...",
			"email_verified": true,
			"personal_code": "EE:EID:31111111234",
			"personal_code_verified": true,
		},
		{
			"sub": "0ab75adb-3333-46d7-22222-3333333",
			"name": "Teise Lapse Nimi",
			"email": "...@...",
			"email_verified": true,
			"personal_code": "EE:EID:41111111234",
			"personal_code_verified": true,
		}
	]
}

```

Ja lisaks vastav OpenID `scope`, millele ligipääsu küsida.

**Comment by joellimberg** [comment]
Kas sellel teemal on mingeid mõtteid või uudiseid? Muudatused võtavad arusaadavalt aega, aga abiks oleks ka mingi eelinfo/dokumetatsioon.

**Comment by Fornacula** [comment]
Vastav scope sai lisatud ja sellekohane info dokumentatsioonis:
test-keskkond: https://test.harid.ee/et/pages/dev-info
live-keskkond: https://harid.ee/et/pages/dev-info
