### ISSUE TITLE
userinfo_endpoint vastusesse ees- ja perekonnanimi

### ISSUE THREAD

**Issue by joellimberg** [hariduspilv/harid#3]
Hetkel vastab `userinfo_endpoint` `"name"` parameetriga, kus on inimese täisnimi ühel väljal.

Kasulik oleks lisaks sellele saada ka eraldi `name_first` ja `name_last` väljad (mis on HarID-s eraldi olemas).

**Comment by Fornacula** [comment]
Versioonis 2.1.0 on eraldatud väljad `given_name` ja `family_name`
