### ISSUE TITLE
Poolikud telefoninumbrid

### ISSUE THREAD

**Issue by joellimberg** [hariduspilv/harid#4]
Kui kasutajal ei ole telefoninumbrit:

<img width="576" alt="screen shot 2018-05-26 at 17 58 01" src="https://user-images.githubusercontent.com/875872/40577448-64634422-610e-11e8-9e07-69391cfc8687.png">

… tagastab API siiski selle pooliku (ja kasutu) info, ehk vaikimisi riigi suunakoodi:

`"phone_number":"+372 "`

**Comment by Fornacula** [comment]
Peaks olema korras versiooniga 2.0.1: https://github.com/hariduspilv/harid/commit/b719cc8da5d1744edd10f49a60e6a26c26df4020
Sulgen.
