### ISSUE TITLE
HarID konto loomise / sisse logimise protsess uutele kasutajatele

### ISSUE THREAD

**Issue by joellimberg** [hariduspilv/harid#6]
- Kui saabuda HarID lehele X rakendusest, eesmärgiga X rakendusse sisse logida
- …on võimalik sisse logida Mobiil-ID-ga
- …aga seejärel on kohustuslik meiliaadressi sisestamine ning meilis kinnituslingi klõpsamine
- … mis kõik teeb HarID kaudu sisse logimise protsessi keerulisemaks, kui see olema peaks

Kasutaja peaks saama meiliaadressit mitte sisestada — seda ei ole turvaliseks autentimiseks vaja.

**Comment by Fornacula** [comment]
Põhi-põhjused, miks e-post on kohustuslik kõigile kasutajatele:

1. Alaealiste autentimine, kel pole alati Mobiil-ID või ID-kaardiga autentimise võimalust
2. Parooli taastamise või konto lahtilukustamise üheks pidepunktiks on e-mail
3. Teiste riikide kodanike autentimise võimaldamiseks on e-post üks lahendus
4. Täiendav turvameede - väldib (küll vähetõenäolist) olukorda, kus ID-kaardi/Mobiil-ID paroole teadev ründaja saab luua teisele isikule konto ja seda ise kasutada (sel juhul on tarvis ründajal ligipääsu ka konto omaniku postkastile, milles on konto kinnituslingiga kiri).

Kui teha tugevate autentimisvahendite (Mobiil-ID ja ID-kaart) puhul konto loomises taoline erand, peab kasutaja ka tulevikus logima HarIDisse alati tugeva autentimisvahendiga (nii kaua, kuniks ta pole sisestanud enda kontole emaili-aadressi). Need on aga üldiselt alati ka e-teenustes pakutud variandid ja seega ei ole HarIDil seal vahel nö vahemehena väga palju mõtet.

**Comment by joellimberg** [comment]
Kiire kommentaar 4. kohta — selles stsenaariumis saab ründaja ikkagi teisele isikule konto teha, lisades sinna profiili lihtsalt enda meiliaadressi.

(Ja seejärel saab ta võõrast kontot — mis on isikukoodiga seotud — oma meiliaadressi kaudu sisse logides igavesti ise _ära kasutada_)

---

Mõistan seda, et meiliaadress lihtsustab teatud protsesse, aga teistpidi see just vähendab turvalisust — tugeva autentimise asemel on võimalik igaühel võõrale kontole ligi pääseda vaid meilipostkasti ligipääsu omades. Ehk, teistpidi sõnastades: tugev autentimine muutub hoopis nõrgemaks, kui samale kontole saab alati ligi ka meiliaadressi kaudu.

**Comment by Fornacula** [comment]
Tõsi, see otseselt jah ei "väldi" kirjeldatud olukorda, küll aga on hiljem vähemalt mingigi väike võimalus tõestada, et e-maili konto omanik ja ID-kaart, millega konto seoti, ei käi kokku. Olulisem on siiski sihtgrupp ja sellest tulenevad kasutusjuhud ning mõned kontohalduse protsessid nõuavad e-maili teel suhtlemist.

e-mail on tõesti selles mõttes turvalisust vähendav atribuut, kuid arvestades, et suur hulk kasutajaid võivad olla isikud, kel pole võimalik alati tugevat autentimisvahendit (Mobiil-ID/ID-kaart) lihtsasti kasutada, siis e-maili ja tugeva autentimisvahendi koosmõjus saavutatakse siiski pisut kõrgem usaldusväärsus. Me ei saa siin rääkida eIDAS raamistikust tugevast autentimismeetmest, küll aga "tugevamast autentimismeetmest" kui lihtsalt e-mail/parool.
