### ISSUE TITLE
ID token peaks sisaldama infot selle kohta, kas kasutaja autentis ennast HarID-s tugevalt või parooliga

### ISSUE THREAD

**Issue by joellimberg** [hariduspilv/harid#8]
Hetkel on kõikidel kasutajatel, kes on konto ID-kaardi/M-ID'ga autentinud alati userinfo vastuses `"personal_code_verified": true` — ka siis, kui sisselogimine toimus salasõna kasutades; ja ID token ei sisalda infot autentimise kohta.

Kasutada saaks `amr` ja/või `acr` väljasid ID tokenis: https://connect2id.com/blog/standard-authentication-methods & http://openid.net/specs/openid-connect-core-1_0.html#acrSemantics

**Comment by Fornacula** [comment]
Nüüdseks on juurde lisatud uus atribuud `strong_session`, mis annab infot kasutaja parasjagu aktiivse sessiooni autentimisvahendi kohta (väärtus on _true_ kui kasutatud on tugevat autentimisvahendit (Mobiil-ID/ID-kaart) ning _false_ muudel juhtudel. Täpsem info siin: https://harid.ee/et/pages/dev-info

**NB!** `personal_code_verified` väli kaob ära järgmise tarne paigaldamisel (versioon 2.2.2). Sama info sisaldub juba väljal `personal_code` nagunii- kui vastaval atribuudil on väärtus olemas, annab see juba mõista, et kasutaja on vähemalt korra kasutanud tugevat autentimisvahendit (või on lapse puhul vanem kinnitanud Rahvastikuregistri andmed ja sidunud seeläbi lapse kontole külge lapse isikukoodi).

**Comment by priit** [comment]
Igaks juhuks mainin, et 'amr' on samuti toetatud, täpsemalt test.harid.ee dokumendis (https://test.harid.ee/et/pages/dev-info dokumendist): You can use standard way by ID token where "arm" value is either "pwd" (password auth) or "pop" (mobiil-ID/ID-card auth).

**Comment by priit** [comment]
ID tokeni põhiteema on lahendatud lives aasta alguses, see osa on minu teada lukus alates jaanuari lõpust.

Teemaväliste küsimuste osas punktide kaupa:

* Õpilane saab ise luua omale konto aga lapsevanem siiski peab seda siduma oma töölaualt (tugevalt tuvastatuna).

* Isegi kui vanem kasutab sidumise/kutse tegemise ajal kellegi teise lapse eposti, siis eposti omanik peab selle enne kasutamist kinnitama. Isikukoode ei saa keegi HarID-sse manuaalselt ise kasutajaliidese kaudu sisestada, need tulavad kas X-tee kaudu Rahvastikuregistrist või ID-kaardi/Mobiil-ID teenustest. Isikukood tuleb tugevalt tuvastatud vanema kaudu ja eposti kinnitab eposti valdaja (ehk õpilane) iseseisvalt.

* Selles osas tugineb HarID Rahvastikuregistri poolt edastatud andmetele. Meie teada täna Rahvastikuregister edastab ka täiskasvanud lapsi. Kuna see võib tekitada igapäevaselt veidi segadust, siis minuteada on HarID-l plaanis täiskasvanud laste sidumise osa eemaldada täiskasvanud laste osas välja arvatud eeskoste puhul.

**Comment by joellimberg** [comment]
@priit 2 jätku-küsimust:

Kas kooli/õppeasutuse administraator saab kuidagi kooliga seotud kasutajate kontosid muuta. Näiteks meiliaadressi lisada/eemaldada/muuta?

Ja _lapsevanem → õpilane_ seose puhul täpsustuseks: kas saan õigesti aru, et teoorias on võimalik selline stsenaarium, et lapsevanem teeb õpilasele konto, aga kasutab seda ise (kui lisab lapse kontole oma meiliaadressi, ja saab siis järelikult selle kaudu ka sisse logida)?

**Comment by priit** [comment]
Kooli/õppeasutuse adminstraator ei saa HarID kasutaja kontosid muuta. Ei saa eposti lisada/eemaldada ega muuta. Ka HarID enda teenuse administraatorid ei saa eposti muuta/lisada/kustutada.

HarID saab kasutada korraga ainult ühte eposti aadressi läbivalt kogu süsteemis, ehk lapsevanem ei saa kasutada oma enda eposti aadressi uuesti lapse konto loomiseks. Kui lapsevanem kutsub lapse HarID kasutama, peab ta uue konto looma uue eeldatavasti lapse eposti aadressiga. Kui lapsevanem ei soovi lapsele kontot luua, siis võib suunata lapse @eesti.ee aadressi enda eposti kontole või kui kasutab gmail.com teenust, kus kirjad saabuvad samale aadressile + märgiga, ehk lapse.vanem@gmali.com sama kui lapse.vanem+01@gmail.com, siis lapsevanem ei pea uut füüsilist eposti kontot haldama aga HarID soovib iga konto kohta ühte unikaalset eposti aadressi läbivalt.
