### ISSUE TITLE
Telefoninumbri valideerimise veateade konto uuendamise lehel

### ISSUE THREAD

**Issue by joellimberg** [hariduspilv/harid#9]
Sisestades telefoninumbri kujul "56 123 123" (ehk siis tühikutega), ilmub teade:

<img width="598" alt="screen shot 2018-05-30 at 15 23 19" src="https://user-images.githubusercontent.com/875872/40719857-91444e5c-641d-11e8-924e-2815855e4c3f.png">

**Comment by Fornacula** [comment]
Vearaport arendajale edastatud, aitäh!

**Comment by Fornacula** [comment]
Probleemile jälile jõutud ning järgmise tarnega tuleb fix.

**Comment by Fornacula** [comment]
Parandus nii test- kui toodanguversioonis üleval. Kuna läbitestimine oli edukas, siis sulgen selle issue.

**Comment by joellimberg** [comment]
Üks seotud aga mitte kuigi kriitiline teema:

kui kasutaja soovib lisada mitu telefoninumbrit (meie süsteemis tuleb seda ette tihedamini kui arvata võiks), siis seda sisestatakse tavapäraselt koma (või semikooloniga) eraldatult:

<img width="314" alt="screen shot 2018-06-07 at 15 57 08" src="https://user-images.githubusercontent.com/875872/41100994-7f91363a-6a6b-11e8-9202-d744aba8c837.png">

Praegune telefoninumbri-puhastamise mehhanism aga teeb siis seda, et eemaldab koma, ja salvestakse number nt "561231236111222"

**Comment by Fornacula** [comment]
Hea tähelepanek, lisasime selle info praegu aga iceboxi tuleviku tarbeks, st lähiajal seda fixima ei hakka.
